# 在 Kubernetes官方文件 中也提到，雖然 Replica Set 提供更彈性的 selector，
# 並不推薦開發者直接使用 kubectl create 等指令創建 Replica Set 物件，
# 而是透過 Deployment 來創建新的 Replica Set。
apiVersion: apps/v1 # for kubectl versions >= 1.9.0 use apps/v1
kind: ReplicaSet
metadata:
  name: my-replica-set
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
    matchExpressions:
      - {key: env, operator: In, values: [dev]}
      - {key: env, operator: NotIn, values: [prod]}
  template:
    metadata:
      labels:
        app: hello-pod-v1
        env: dev
        version: v1
    spec:
      containers:
      - name: my-pod
        image: zxcvbnius/docker-demo
        ports:
        - containerPort: 3000